language: cpp
os:
- linux
sudo: false
compiler: clang
env:
  global:
  - HASH=master
  - REPO=https://github.com/Bilibili/jni4android.git
addons:
  apt:
    packages:
    - flex
before_script:
- ./get-deps.sh