language: cpp
os:
- linux
compiler: clang
sudo: false
env:
  global:
  - HASH=master
  - REPO=https://github.com/Bilibili/jni4android.git
addons:
  apt:
    packages:
    - flex
before_script:
- ./get-deps.sh
script:
- ./configure --cxx=clang++ && make && make test