language: cpp
os:
- osx
sudo: false
compiler: clang
env:
  global:
  - HASH=master
  - REPO=https://github.com/Bilibili/jni4android.git
before_install:
- brew update
- brew outdated flex || brew upgrade flex
- brew outdated bison || brew upgrade bison
before_script:
- ./get-deps.sh