language: cpp
os:
- osx
sudo: false
env:
  global:
  - HASH=master
  - REPO=https://github.com/Bilibili/jni4android.git
before_install:
- brew update
- brew outdated flex || brew upgrade flex
- brew outdated bison || brew upgrade bison
before_script:
- git clone --depth=50 --branch=$HASH $REPO
- cd jni4android
- ./get-deps.sh
script:
- ./configure && make && make test