language: cpp
os:
  - linux
sudo: required
env:
  global:
  - HASH=master
  - REPO=https://github.com/Bilibili/jni4android.git
script:
- git clone --depth=50 --branch=$HASH $REPO
- cd jni4android
- "./configure --cxx=clang++"
- make test
before_install:
  - sudo apt-get update
  - sudo apt-get install git
  - sudo apt-get install make
  - sudo apt-get install clang
  - sudo apt-get install flex
  - sudo apt-get install bison
  - clang++ --version
  - flex --version
  - bison --version
